version: '3.7'
services:
  # redis:
  #   image: redis:7
  #   container_name: superset_cache
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   volumes:
  #     - redis:/data
  #   networks:
  #     - superset

  db:
    env_file: .env
    image: postgres:14
    container_name: trading_db
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - trading

volumes:
  db:
    external: false
  # redis:
  #   external: false

networks:
  trading:
    name: shared-trading
