version: '3.7'
services:
  # redis:
  #   image: redis:7
  #   container_name: superset_cache
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   volumes:
  #     - redis:/data
  #   networks:
  #     - superset

  trading_db:
    image: postgres:14
    container_name: trading_db
    env_file: docker/.env-trading
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    external: false
  # redis:
  #   external: false
