export enum ENUM_TRADING_SESSION_STATUS {
  CREATED = 'CREATED',
  TO_START = 'TO_START',
  STARTING = 'STARTING',
  IN_PROGRESS = 'IN_PROGRESS',
  TO_END = 'TO_END',
  ENDING = 'ENDING',
  ENDED = 'ENDED',
}
